version: '3'

services:
  graph:
    image: zzglider/mygraphdb:prc2021
    container_name: mygraph
    ports:
      - '7200:7200'
    networks: 
      - backFront
    restart: 
      always
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - authFront
    restart: 
      always 
  api:
    image: prc2021/marvel_api
    container_name: api
    networks:
      - backFront
    restart: 
       always   
  view: 
    image: prc2021/marvel_front
    container_name: view
    ports:
        - '3001:3001'
    networks:
      - 'backFront'
      - 'authFront'   
  auth:
    image: prc2021/auth
    container_name: auth
    ports:
        - '5000:5000'
    depends_on: 
      - view
      - mongo   
    networks:
      - 'authFront'    
networks:
    backFront:
    authFront:                
